---
title: "heatmap_cluster_analysis"
output:
  pdf_document: default
  html_document: default
date: '2024-10-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/home/molinerislab/Calautti_RICTOR/dataset/v1")
library(clusterProfiler)
suppressMessages(library(org.Hs.eg.db))
suppressMessages(library(DOSE))
library(enrichplot)
library(ggplot2)
library(stringr)
```

```{r, echo=FALSE}
k=3

p<-readRDS("heatmap.Rds")
gene_clusters<-cutree(p$tree_row, k)
sets <- list(names(which(gene_clusters==1)),
             names(which(gene_clusters==2)),
             names(which(gene_clusters==3))
)

universe<-read.table("GEP.count.cpm.expressed_genes")$V1
universe <- bitr(universe, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)$ENTREZID
```

```{r}
get_enrich_GO<-function(genes,ont){
    genes <- bitr(genes, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)
    ego <- enrichGO(gene          = genes$ENTREZID,
                universe      = universe,
                OrgDb         = org.Hs.eg.db,
                ont           = ont,
                maxGSSize     = 500,
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE,
                pool          = TRUE
    )
    return(ego)
}

get_enrich_DO<-function(genes,ont){
    genes <- bitr(genes, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)
    ego <- enrichDO(gene          = genes$ENTREZID,
                universe      = universe,
                ont           = ont,
                maxGSSize     = 500,
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.5,
                qvalueCutoff  = 0.5,
                readable      = TRUE,
    )
    return(ego)
}
```

```{r plots}

for (i in 1:k) {
  ego <- get_enrich_GO(sets[[i]], "ALL")
  p<-dotplot(ego, showCategory = 30, title=paste("GO enrichment for cluster ", i))+scale_y_discrete(labels=function(x) str_wrap(x, width=60))
  ggsave(paste("heatmap_cluster_", i, "_GO.pdf", sep = ""), width = 7, height = 12)
  print(p)
 
  edo <- get_enrich_DO(sets[[i]], "DO")
  p<-dotplot(edo, showCategory = 30, title=paste("DO enrichment for cluster ", i))+scale_y_discrete(labels=function(x){str_wrap(x, width=60)})
  ggsave(paste("heatmap_cluster_", i, "_DO.pdf", sep = ""), width = 7, height = 12)
  print(p)
}

```


