#
# RNA-seq analysis pipeline
#
# --------------#
# Configuration #
# --------------#
import os

configfile: "config.yaml"

REFERENCE_ROOT=os.environ.get("REFERENCE_ROOT")

# GENERAL SETUP ---
CONDA_ROOT=config["CONDA_ROOT"]
CONDA_ACTIVATE="set +u; source %s/etc/profile.d/conda.sh ; conda activate ; conda activate" % config["CONDA_ROOT"]
RAW_DATA_DIR= ["."]

# GENCODE ---
GENCODE_DIR=REFERENCE_ROOT+"/bioinfotree/task/gencode/dataset/"+config["GENCODE"]["SPECIES"]+"/"+config["GENCODE"]["VERSION"]
GENCODE_GENOME_FASTA=GENCODE_DIR+"/"+config["GENCODE"]["GENOME"]+".genome.fa"
GENCODE_ANNOTATION_GTF=GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".gtf"
GENCODE_ANNOTATION_BED=GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".bed"


# visualization param ---
GFF3_MIN_WINDOW_READS = "100"
BIGWIG_BIN_SIZE = "50"
BEDGRAPH_FILTER = "100"
#REPEAT_FAMILY_RAND_REPETITION=10 


# featurecounts param ---
FEATURECOUNTS_PARAM = config["FEATURECOUNTS_PARAM"] + " -s" + config["STRANDED"]
if config["LAYOUT"] == "PAIRED":
    FEATURECOUNTS_PARAM += " -p -C --countReadPairs" 
# -O allowMultiOverlap
LCPM_PRIOR_COUNT = 0.25           # *standard of edgeR*
LTPM_PRIOR_COUNT = 0.0001

#TODO implement automatic handling of single/paired end layout  
# LAYOUT ---
# if config["LAYOUT"] == "SINGLE":
# 	ruleorder: umitools_extract_se > umitools_extract_pe
# 	ruleorder: trimgalore_se > trimgalore_pe
# elif config["LAYOUT"] == "PAIRED":
# 	ruleorder: umitools_extract_pe > umitools_extract_se
# 	ruleorder: trimgalore_pe > trimgalore_se

# STAR ---
#if config["STAR"]["INDEX"] is None:
#        STAR_INDEX=GENCODE_DIR+"/"+config["GENCODE"]["GENOME"]+".star_index/"+config["STAR" ]["INDEX_PREFIX"]
#else:
#        STAR_INDEX=config["STAR"]["INDEX"]

# Samples ---
SAMPLES, = glob_wildcards("fastq/{sample}_R1.fastq.gz")

# Include modules ---
include: "../../local/rules/generic_rules.smk"
include: "../../local/rules/trim.smk"
include: "../../local/rules/star_alignment.smk"
include: "../../local/rules/count.smk"
include: "../../local/rules/rseqc.smk"
include: "../../local/rules/DGE.smk"
include: "../../local/rules/venn_heatmap.smk"

if os.path.exists("Snakefile_versioned.sk"):
    include: "Snakefile_versioned.sk"


# Rule ALL ---

rule all:
    input:
        #"GEP.count.exp_filter.ltmm.gz" 
        "GEP.count.exp_filter.ltmm.xlsx",
        "multiqc_report.html",
        "multiqc_report.rseqc.html",
        "usable_reads.txt.xlsx" 


# ALL_infer_experiment: $(addprefix rseqc/$(FASTQ_FILTERING)/,$(addsuffix .infer_experiment.txt, $(SAMPLES)))
# 	matrix_reduce 'rseqc/fastq/*.infer_experiment.txt' -l '$^' | grep . | perl -lne 'if(m/^>/){print; next} print "$$1\t$$2" if m/("[^:]+|failed to determine):\s+(.*)/' | fasta2tab | tab2matrix -r sample > $@
rule ALL_infer_experiment:
    input: 
        expand("rseqc/{samples}.infer_experiment.txt", samples= SAMPLES)
    output: 
        "ALL_infer_experiment"
    shell:"""  
        matrix_reduce 'rseqc/*.infer_experiment.txt' -l '{input}' | grep . | perl -lne 'if(m/^>/){{print; next}} print "$1\t$2" if m/("[^:]+|failed to determine):\s+(.*)/' | fasta2tab | tab2matrix -r sample > {output}
    """ 

# -------------- #
# Multiqc report #
# -------------- #

rule multiqc_fastq:
    input:
        fastqc_html=expand("fastqc/{fastq_filtering}/{s}_{p}_fastqc.html", s=SAMPLES, p=("R1","R2"), fastq_filtering=config["FASTQ_FILTERING"]),
        fastqc_zip=expand("fastqc/{fastq_filtering}/{s}_{p}_fastqc.zip",  s=SAMPLES, p=("R1","R2"), fastq_filtering=config["FASTQ_FILTERING"])
    output:
        "multiqc_report.html"
    params:
        data_dir = RAW_DATA_DIR
    shell:"""
        multiqc -f -n {output} {params.data_dir}
    """

rule multiqc_report_rseqc:
    input:
        expand("rseqc/{sample}.geneBodyCoverage.txt", sample=SAMPLES),
        expand("rseqc/{sample}.infer_experiment.txt", sample=SAMPLES),
        expand("rseqc/{sample}.junctionSaturation_plot.r", sample=SAMPLES),
        expand("rseqc/{sample}.pos.DupRate.xls", sample=SAMPLES),
        expand("rseqc/{sample}.read_distribution.txt", sample=SAMPLES),
        expand("rseqc/{sample}.bam_stat.txt", sample=SAMPLES),
        expand("fastqc/{fastq_filtering}/{sample}_R1_fastqc.html", sample=SAMPLES, fastq_filtering=config["FASTQ_FILTERING"])
    output:
        "multiqc_report.rseqc.html"
    params:
        data_dir = RAW_DATA_DIR
    shell: """
        multiqc -f -n {output} {params.data_dir}
    """

# rule multiqc_alignment:
#     input:
#         fastqc_html=expand("fastq/{fastq}_fastqc.html", fastq=FASTQ_FILES),
#         fastqc_zip=expand("fastq/{fastq}_fastqc.zip", fastq=FASTQ_FILES),
#         bam=expand("bam/{sample}.bam", sample=SAMPLES),
#         bai=expand("bam/{sample}.bam.bai", sample=SAMPLES)
#     output:
#         report="multiqc_report.alignment.html",
#         star="multiqc_report.alignment_data/multiqc_star.txt"
#     shell:
#         "multiqc -f -n {output} ."

# ----- #
# RSeQC #
# ----- #
rule gene_body_coverage:
    input:
        bam="star/{sample}.bam",
        bai="star/{sample}.bam.bai",
        housekeeping_genes=GENCODE_DIR+"/rseqc.HouseKeepingGenes.bed.gz"
    output:
        text="rseqc/{sample}.geneBodyCoverage.txt",
        rscript="rseqc/{sample}.geneBodyCoverage.r"
    params:
        docker_data_dir=config["DOCKER_DATA_DIR"],
        scratch_dir=config["TMPDIR"]
    shell: """
        mkdir -p `dirname {output.text}`; 
        docker run -u `id -u`:`id -g` --rm \
            -v {params.docker_data_dir}:{params.docker_data_dir} \
            -v {params.scratch_dir}:{params.scratch_dir} \
            quay.io/biocontainers/rseqc:4.0.0--py38h0213d0e_0  \
            bash -c "cd `echo $PWD`; geneBody_coverage.py -i {input.bam} -r <(zcat {input.housekeeping_genes}) -o rseqc/{wildcards.sample}"; 
        sed -i 's|Aligned.sortedByCoord.out|{wildcards.sample}|' {output.text}
    """

rule plot_gene_body_coverage_summary:
    input:
        all_gene_body_cov=expand(
            "rseqc/{sample}.geneBodyCoverage.txt",
            sample=SAMPLES
        ),
        rscript="../../local/src/plotGeneBodyCovSummary.R"
    output:
        plt_all="rseqc/geneBodyCoverage.all.pdf",
        plt_summary="rseqc/geneBodyCoverage.summary.pdf"
    shell:
        "{CONDA_ACTIVATE} rstudio_Rv4.0.3; "
        "Rscript --vanilla {input.rscript} rseqc"

rule read_distribution:
    input:
        bam="star/{sample}/Aligned.sortedByCoord.out.bam",
        rseqc_ref_bed=GENCODE_ANNOTATION_BED
    output:
        text="rseqc/{sample}.read_distribution.txt"
    params:
        docker_data_dir=config["DOCKER_DATA_DIR"],
        scratch_dir=config["TMPDIR"]
    shell:
        """
        mkdir -p `dirname {output}`; 
        docker run -u `id -u`:`id -g` --rm \
        -v {params.docker_data_dir}:{params.docker_data_dir} \
        -v {params.scratch_dir}:{params.scratch_dir} \
        quay.io/biocontainers/rseqc:4.0.0--py38h0213d0e_0  \
        bash -c "cd `echo $PWD`; \
        read_distribution.py -i {input.bam} -r {input.rseqc_ref_bed} > {output.text}"
        """

rule plot_read_distribution:
    input:
        all_gene_body_cov=expand(
            "rseqc/{sample}.read_distribution.txt",
            sample=SAMPLES
        ),
        rscript="../../local/src/plotReadDistributionSummary.R"
    output:
        "rseqc/reads_distribution_summary.pdf",
    shell:
        "{CONDA_ACTIVATE} rstudio_Rv4.0.3; "
        "Rscript --vanilla {input.rscript} rseqc"


# -------------- #
# Feature counts #
# -------------- #
def featurecounts_input(wildcards):
	#retval=[]
	for sample in SAMPLES:
		yield("STAR/{w.fastq_filtering}/{s}/Aligned.sortedByCoord.out.bam".format(s=sample, w=wildcards))
	#return(retval)

# featurecouts già gestito da ribo_read_counts

# rule featurecounts:
# 	input: 
# 		featurecounts_input
# 	output: 
# 		counts="{fastq_filtering}.featurecounts",
# 		summary="{fastq_filtering}.featurecounts.summary"
# 	params: 
# 		gtf = REFERENCE_COUNT_GTF,
# 		params = FEATURECOUNTS_PARAM,
# 		TMPDIR = TMPDIR
# 	threads: 12
# 	shell:"""
# 		featureCounts -o {output.counts} -a {params.gtf} {params.params} --tmpDir {params.TMPDIR} -T {threads} {input}
# 	"""


#TODO move in correct .mk after https://www.pivotaltracker.com/story/show/188249716
"""
.META: *.toptable_clean.ALL_contrast.*mark_seqc.*gz 
	1	contrast
	2	GeneID
	3	logFC
	4	Pvalue
	5	Pvalue_adj
	6	significance

.META: *.toptable_clean.ALL_contrast.*gz 
	1	contrast
	2	GeneID
	3	logFC
	4	Pvalue
	5	Pvalue_adj

.META: *.toptable_clean*.gz
	1	GeneID
	2	logFC
	3	Pvalue
	4	Pvalue_adj

.META: GEP.count.*.metadata.exp_genes_condition.gz
	1	condition
	2	gene
	3	avg_exp
	4	median_exp
	5	min_exp

"""
rule count_significance:
    input:
        "edger.toptable_clean.ALL_contrast.mark_seqc.gz"
    output:
        "edger.toptable_clean.ALL_contrast.mark_seqc.count"
    shell:
        """
        bawk '{{print $1, $6}}' {input} | symbol_count | tab2matrix -r contrast > {output}
        """
