                                                                                                           
#                               ▄▄                  ▄▄▄▄▄▄    ▄▄▄   ▄▄     ▄▄       ▄▄▄▄    ▄▄▄▄▄▄▄▄    ▄▄▄▄                
#                               ██                  ██▀▀▀▀██  ███   ██    ████    ▄█▀▀▀▀█   ██▀▀▀▀▀▀   ██▀▀██ 
# ▄▄█████▄  ██▄████▄   ▄█████▄  ██ ▄██▀    ▄████▄   ██    ██  ██▀█  ██    ████    ██▄       ██        ██    ██         
# ██▄▄▄▄ ▀  ██▀   ██   ▀ ▄▄▄██  ██▄██     ██▄▄▄▄██  ███████   ██ ██ ██   ██  ██    ▀████▄   ███████   ██    ██         
#  ▀▀▀▀██▄  ██    ██  ▄██▀▀▀██  ██▀██▄    ██▀▀▀▀▀▀  ██  ▀██▄  ██  █▄██   ██████        ▀██  ██        ██    ██         
# █▄▄▄▄▄██  ██    ██  ██▄▄▄███  ██  ▀█▄   ▀██▄▄▄▄█  ██    ██  ██   ███  ▄██  ██▄  █▄▄▄▄▄█▀  ██▄▄▄▄▄▄   ██▄▄██▀ 
#  ▀▀▀▀▀▀   ▀▀    ▀▀   ▀▀▀▀ ▀▀  ▀▀   ▀▀▀    ▀▀▀▀▀   ▀▀    ▀▀▀ ▀▀   ▀▀▀  ▀▀    ▀▀   ▀▀▀▀▀    ▀▀▀▀▀▀▀▀    ▀▀▀██  
#                                                                                                           ▀  
#                   +-+-+-+-+-+ +-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+
#                   |(|n|o|t|)| |j|u|s|t| |a|n|o|t|h|e|r| |R|N|A|-|s|e|q| |p|i|p|e|l|i|n|e|
#                   +-+-+-+-+-+ +-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+ +-+-+-+-+-+-+-+-+
#                                         __    __    __    __
#                                        /  \  /  \  /  \  /  \
#_______________________________________/  __\/  __\/  __\/  __\_______________________________________________
#______________________________________/  /__/  /__/  /__/  /__________________________________________________
#                                      | / \   / \   / \   /  \  \____
#                                      |/   \_/   \_/   \_/    \    o \
#                                                               \_____/--<

###########
# Import  #
###########

import os

###########
# Config  #
###########

container: "/home/aleone/snakeRnaSeq/local/container/transcript_analysis.sif"   
configfile: "config.yaml"

############
# Samples  #
############

SAMPLES, = glob_wildcards("fastq/{sample}_R1.fastq.gz")
EXCLUDE_DIRS = ['fastq_trimmed', 'unmapped', 'unclassified', 'ribo.ex']
SAMPLES = [s for s in SAMPLES if not any(s.startswith(d) or f'/{d}/' in s for d in EXCLUDE_DIRS)]

print("Detected samples:", SAMPLES)
RAW_DATA_DIR = "fastq/"

###################
# Reference root  #
###################

REFERENCE_ROOT=os.environ.get("REFERENCE_ROOT")

###########
# Params #
###########

#############
# Genecode  #
#############

GENCODE_DIR=REFERENCE_ROOT+"/bioinfotree/task/gencode/dataset/"+config["GENCODE"]["SPECIES"]+"/"+config["GENCODE"]["VERSION"]
GENCODE_GENOME_FASTA=GENCODE_DIR+"/"+config["GENCODE"]["GENOME"]+".genome.fa"
GENCODE_ANNOTATION_GTF=GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".gtf"
GENCODE_ANNOTATION_BED=GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".bed"
RSEQC_REF_BED=GENCODE_DIR+"/basic.annotation.bed"
GENOME_KEY = "GRCh"

##########
# Star  #
##########

STAR_VERSION = shell("STAR --version", read=True).strip()
STAR_GENOME_DIR = GENCODE_DIR+"/"+config["GENCODE"]["GENOME"]+".star_index/"+STAR_VERSION
FEATURECOUNTS_PARAM = config["FEATURECOUNTS_PARAM"] + " -s" + config["STRANDED"]
LCPM_PRIOR_COUNT = 0.25 
LTPM_PRIOR_COUNT = 0.0001


##############
reference_fasta_path     = f"{config['REFERENCE_DIR']}/{config['GENOME_ASSEMBLY']}.genome.fa"
annotation_gtf_path      = f"{config['REFERENCE_DIR']}/46/primary_assembly.annotation.gtf" #TODO: make dynamic 46
transcriptome_fasta_path = f"{config['REFERENCE_DIR']}/gencode.v{config['GENCODE_RELEASE']}.transcripts.fa"

############
# Include  #
############

if os.path.exists("Snakefile_versioned.sk"):
    include: "Snakefile_versioned.sk"

include: "../../local/rules/alignment_post.smk" #DONE
include: "../../local/rules/utils.smk" #DONE
include: "../../local/rules/qc.smk" #DONE
include: "../../local/rules/trim.smk" #DONE
include: "../../local/rules/star_alignment.smk" #DONE
include: "../../local/rules/bwa_alignment.smk" #DONE
include: "../../local/rules/count.smk"
include: "../../local/rules/rseqc.smk" #DONE
include: "../../local/rules/DGE.smk" #DONE
include: "../../local/rules/venn_heatmap.smk"
include: "../../local/rules/metagenome.smk"
include: "../../local/rules/Isoforms.smk"
include: "../../local/rules/reference.smk"
  
###############
# Ruleorder  #
###############

if config["LAYOUT"] == "SINGLE":
    ruleorder: fastp_se > fastp_pe
    ruleorder: trim_galore_se > trim_galore_pe
    ruleorder: star_align_se > star_align_pe
elif config["LAYOUT"] == "PAIRED":
    ruleorder: fastp_pe > fastp_se
    ruleorder: trim_galore_pe > trim_galore_se
    ruleorder: star_align_pe > star_align_se
    
ruleorder: featurecounts > split_bam_ribo

##############
# Rules ALL  #
##############

rule all:
    input: 
        "GEP.count.exp_filter.ltmm.gz.xlsx",
        "multiqc_report.html",
        "multiqc_report.rseqc.html",
        "usable_reads.txt.xlsx" 

rule all_multiqc:
    input:
        "multiqc_report.html",
        "multiqc_report.rseqc.html",
        "multiqc_report.alignment.html"


rule all_fastq_trimmed:
    input:
        expand("fastq/fastq_trimmed//{sample}_R1.fastq.gz",sample=SAMPLES)

rule ALL_infer_experiment:
    input: 
        expand("rseqc/{samples}.infer_experiment.txt", samples= SAMPLES)
    output: 
        "ALL_infer_experiment"
    shell: r"""  
        matrix_reduce 'rseqc/*.infer_experiment.txt' -l '{input}' | grep . | perl -lne 'if(m/^>/){{print; next}} print "$1\t$2" if m/("[^:]+|failed to determine):\s+(.*)/' | fasta2tab | tab2matrix -r sample > {output}
    """ 

rule ALL_star:
    input:
        expand("star/{sample}.bam", sample=SAMPLES)


rule all_fastq_unmapped:
    input:
        expand("fastq_unmapped/{sample}_R1.fastq.gz", sample=SAMPLES),
        expand("fastq_unmapped/{sample}_R2.fastq.gz", sample=SAMPLES)


rule all_star_sp:
    input:
        expand("Results/pass2/{sample}/{suffix}",
               genome=[config["GENCODE"]["ASSEMBLY"]],
               sample=SAMPLES,
               suffix=["Aligned.sortedByCoord.out.bam", "ReadsPerGene.out.tab"])

rule all_merge_filter_sj:
    input:
        expand("Results/pass1/merged_filtered_SJ.out.tab")


rule all_star_twopass_basic:
    input:
        expand("star_2pass/{sample}/Aligned.sortedByCoord.out.bam",
               sample=SAMPLES)

rule all_kallisto:
    input:
        expand("kallisto/{sample}/abundance.tsv", sample=SAMPLES) 

rule all_spladder:
    input:
        expand("spladder/merged/spladder/genes_graph_conf3.merge_graph.pickle", sample=SAMPLES),
        expand("spladder/quantification/spladder/genes_graph_conf3.quant.pickle", sample=SAMPLES)

rule all_stringtie:
    input:
        expand("stringtie/{sample}/quant/abund.tab", sample=SAMPLES)

rule all_samb_sort:
    input:
        expand("sambamba/{sample}.sorted.bam", sample=SAMPLES)

rule all_kraken:
    input:
        expand("kreports/{S}.k2report", S=SAMPLES),
        expand("koutputs/{S}.kraken2", S=SAMPLES)


rule all_bracken:
    input:
        expand("breports/{S}.breport", S=SAMPLES),
        expand("boutputs/{S}.braken", S=SAMPLES)

rule all_fastq_unclassified:
    input:
        expand("fastq_unclassified/{sample}_R1.fastq.gz", sample=SAMPLES),
        expand("fastq_unclassified/{sample}_R2.fastq.gz", sample=SAMPLES)

rule all_filter_kraken:
    input:
        expand("koutput_filtered/{sample}.kraken2", sample=SAMPLES)

rule all_k2rfilter:
    input:
        expand("kreports_filtered/{sample}.k2report", sample=SAMPLES)


rule all_filbracken:
    input:
        expand("breports_filtered/{sample}.breport", sample=SAMPLES),
        expand("boutputs_filtered/{sample}.braken", sample=SAMPLES)