#   ___           __ _                    _   _          
#  / __|___ _ _  / _(_)__ _ _  _ _ _ __ _| |_(_)___ _ _  
# | (__/ _ \ ' \|  _| / _` | || | '_/ _` |  _| / _ \ ' \ 
#  \___\___/_||_|_| |_\__, |\_,_|_| \__,_|\__|_\___/_||_|
#                     |___/                                                                             

# ========================
# GENERAL SETUP
# ========================

TMPDIR: "/tmp"  # Temporary directory for intermediate files: set accordingly 
CORES: 6                             # Number of cores to use

# ========================
# EXPERIMENT INFO
# ========================

LAYOUT: "PAIRED"  # SINGLE | PAIRED 
STRANDED: "2"    # 0 -> unstranded, 1 -> forward, 2 -> reverse
aligner: "star"  # star | bwa
TRIMMER: "trim_galore"  # fastp | trim_galore

# ========================
# GENCODE & REFERENCE
# ========================
DATABASE: "gencode" # vectorbase | gencode | custom
GENCODE:
  SPECIES: "hsapiens"      # hsapiens | mmusculus | mmusculus_hsapiens_combined | mosquito
  VERSION: "46"            # 32 | M23
  GENOME: "GRCh38.p14" # GRCh38.primary_assembly | GRCm38.primary_assembly | GRCh38.p14 | GRCm39.primary_assembly | Agambiae
  ANNOTATION: "basic.annotation" # primary_assembly.annotation | basic.annotation

GENOME_ASSEMBLY: "GRCh38.p14"

# ========================
# ALIGNMENT (STAR)
# ========================

STAR:
  # Input / Output
  OUT_SAM_TYPE: "BAM SortedByCoordinate"
  readFilesCommand: "zcat"
  ADDITIONAL_OUTPUT: ""
  quantMode: "GeneCounts TranscriptomeSAM"
  # Alignment Filters
  OUT_FILTER_TYPE: "BySJout"
  OUT_FILTER_MULTIMAP_NMAX: 200           
  OUT_FILTER_MISMATCH_NMAX: 999           
  OUT_FILTER_MISMATCH_NOVER_LMAX: 0.04    
  MULTIMAP_SCORE_RANGE: 1
  # Alignment Splicing/Introns
  ALIGN_SJ_OVERHANG_MIN: 8                
  ALIGN_SJDB_OVERHANG_MIN: 1
  ALIGN_INTRON_MIN: 20
  ALIGN_INTRON_MAX: 1000000
  ALIGN_MATES_GAP_MAX: 1000000
  # Additional Parameters
  sjdbOverhang: 149
  limitSjdbInsertNsj: 1000000
  SAVE_UNMAPPED: "FASTQ" # BAM | FASTQ 
  

METAGENOMICS:
  PRIMARY_HOST:
    # STAR_INDEX: GENCODE_DIR

  HUMAN_FILTER:
    ENABLED: true # set to true if you want to filter out human reads from the unmapped reads (only relevant for metagenomics samples)
    # STAR_INDEX: GENCODE_DIR

# ========================
# TRIMMING
# ========================

FASTP:
  adapter_r1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  adapter_r2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"

TRIM_GALORE:
  PARAM: "" # https://support-docs.illumina.com/SHARE/AdapterSequences/Content/SingleIndexes.htm

# ========================
# COUNTING (FeatureCounts)
# ========================

FEATURECOUNTS_PARAM: "-t exon -g gene_name"
#default count on exons and summarize on gene names, consider -g gene_id
#strandnes and paired-end handled in config.smk
# -O allowMultiOverlap
# -g gene_name
# -s 2
# -p -C ==> paired-end layout

# ========================
# DGE ANALYSIS
# ========================

DGE:
  DGE_TOOL: "edger"
  # FIXED: Added space after colon below
  LIMMA_CONTRASTS: #e.g. LIMMA_CONTRASTS:
        # contrast_name: "contrast"
        # KO_vs_WT: "(KO.ND+KO.HFD)-(WT.ND+WT.HFD)"
  LIMMA_DESIGN_FORMULA: "~0+condition"
  LIMMA_FACTORS: ""
  MIN_NUM_OF_EXPRESSED_SAMPLE: 3
  EXPRESSED_GENES_MIN_CPM: 1
  DGE_CONDITION: "condition"
  LIMMA_CONTRASTS_NAMES: []
MARK_SEQC:
  LOGFC: 1
  PVALUE: 1
  PVALUE_ADJ: 0.05

VENN_CONTRASTS:
  #e.g. TODO better documentation
  #- untreated
  #- vem_4h
  #- vem_24h
  #- res_vem_0.2
  #- res_vem_0.8
  #- res_vem_1.6

HEATMAP:
  COLUMNS: "condition,sh,vem"
  # columns of metadata.txt to add to the heatmap, separated by ,

  N_TOP: "500"
  # number of the top most variant genes to consider for the heatmap

  COLORS: "--pal_set Set3"
  # leave empty if you wish to use the standard colors or specify the custom colorbrewer set to use (default is Set1)

  CLUSTERS: "-r 3 -z 3"
  # indicate the number of clusters the rows (-r) and the columns (-z) will be divided into. 
  # leave empty to have no clusters

# ========================
# VISUALIZATION
# ========================
GFF3_MIN_WINDOW_READS: "100"
BIGWIG_BIN_SIZE: "50"
BEDGRAPH_FILTER: "100"
#REPEAT_FAMILY_RAND_REPETITION=10 

# ========================
# METAGENOMICS (Kraken/Bracken)
# ========================

BRACKEN:
  bracken_read_len: 100
  bracken_min_reads: 5
  bracken_level: "S"

kraken_db: "/home/nobackup/home/reference_data/bioinfotree/task/kraken/k2_pluspf_20250402"
kraken_k2d: "/home/reference_data/bioinfotree/task/kraken/nobackup/k2_pluspf_20250402/taxo.k2d"
kraken_db_nr: "/home/reference_data/bioinfotree/task/kraken/nobackup/k2_nt"
hitgrp: 2 


# ========================
# FEATURE FILTERING
# ========================

feature_filter:
  condition: "disease"
  g1: "D"
  g2: "H"
  use_raw_counts: true
  min_exp: 100
  min_samples_ratio: 0.5

# ========================
# CONTAMINANT / HOST
# ========================

CONTAMINANT_INFO:
  contaminant: ["0"]
  humanID: ["9606"]
  split_by: ["sample_type"]
  split_by_value: [""]
  multiple_files: FALSE

VERSION: "46"

SPECIES: human

UCSC_VERSION: hg38
 

#TODO: put them in the featurecounts section above
# featurecounts param ---
#FEATURECOUNTS_PARAM = config["FEATURECOUNTS_PARAM"] + " -s" + config["STRANDED"]
#if config["LAYOUT"] == "PAIRED":
#    FEATURECOUNTS_PARAM += " -p -C --countReadPairs" 
# -O allowMultiOverlap
#LCPM_PRIOR_COUNT = 0.25           # *standard of edgeR*
#LTPM_PRIOR_COUNT = 0.0001



kraken:
  exclude_classified: True
  include_children: True
  

################
# MAJIQ CONFIG #
################
comparisons :
  - "WT_ND_vs_KO_ND"
  - "WT_HFD_vs_KO_HFD"
  - "KO_ND_vs_KO_HFD"
  - "WT_ND_vs_WT_HFD" 
  