############
# Samples  #
############

import glob
import re
import os

RAW_DATA_DIR = "fastq/"
EXCLUDE_DIRS = ['fastq_trimmed', 'unmapped', 'unclassified', 'ribo.ex']
files = glob.glob(os.path.join(RAW_DATA_DIR, "*.fastq.gz"))

SAMPLES = set()

for filepath in files:
    filename = os.path.basename(filepath)
    
    if any(d in filepath for d in EXCLUDE_DIRS):
        continue
    match = re.search(r'(.+)_R[12](?:_.+)?\.fastq\.gz', filename)

    if match:
        SAMPLES.add(match.group(1))

SAMPLES = sorted(list(SAMPLES))

print("Detected samples:", SAMPLES)

###################
# Reference root  #
###################

REFERENCE_ROOT=os.environ.get("REFERENCE_ROOT")

###########
# Params #
###########

#############
# Genecode  #
#############

GENCODE_DIR=REFERENCE_ROOT+"/dataset/"+config["GENCODE"]["SPECIES"]+"/"+config["GENCODE"]["VERSION"]
GENCODE_GENOME_FASTA=GENCODE_DIR+"/"+config["GENCODE"]["GENOME"]+".genome.fa"
GENCODE_ANNOTATION_GTF=GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".gtf"
gff3 = GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".basic.annotation.gff3"
GENCODE_ANNOTATION_BED=GENCODE_DIR+"/"+config["GENCODE"]["ANNOTATION"]+".bed"
RSEQC_REF_BED=GENCODE_DIR+"/basic.annotation.bed"
GENOME_KEY = "GRCh"

##########
# Star  #
##########

STAR_VERSION = shell("STAR --version", read=True).strip()
STAR_GENOME_DIR = GENCODE_DIR+"/"+config["GENCODE"]["GENOME"]+".star_index/"+STAR_VERSION
FEATURECOUNTS_PARAM = config["FEATURECOUNTS_PARAM"] + " -s" + config["STRANDED"]
LCPM_PRIOR_COUNT = 0.25 
LTPM_PRIOR_COUNT = 0.0001


##############
reference_fasta_path     = GENCODE_GENOME_FASTA
annotation_gtf_path      = GENCODE_ANNOTATION_GTF
transcriptome_fasta_path = GENCODE_DIR + "/"+ "gencode.v" + "config['GENCODE']['VERSION']"+ ".transcripts.fa"
#TODO: REMOVE THOSE PATHS 