#original fastq files were renames with rename 's/_001(?=\.fastq\.gz)//' *.fastq.gz 

rule correct_fastq_names:
    input: "{file}_001.fastq.gz"
    output: "{file}.fastq.gz"
    shell: "echo 'run rename -n 's/_S\d+//' *.fastq.gz and rename 's/_001(?=\.fastq\.gz)//' *.fastq.gz inside fastq/'"

rule filter_exp:
    input:
        "GEP.count.exp_filter.ltmm.gz"
    output:
        "GEP.count.exp_filter.ltmm.no_undeter.gz"
    shell:
        "zless {input} | bawk '{{print $1~13}}' | gzip > {output}"

rule filter_metadata:
    input:
        "metadata.txt"
    output:
        "metadata.no_undeter.txt"
    shell:
        "cat {input} | grep -v 'Undetermined' > {output}"

