# GENERAL SETUP ---
TMPDIR: /mnt/nvme_raid0/tmp
CORES: 6
CONDA_ROOT: /opt/conda/miniconda3
DOCKER_DATA_DIR: /home
NOBACKUP: /home/nobackup/molinerislab/mosquito/bam_saizonou


sample: ["DA01", "DA02", "DA03", "BU01", "BU02", "BU03", "BP02", "BP03", "BP04", "KIS01", "KIS02", "KIS03", "DU01", "DU02", "DU03", "BD01", "BD02", "BD03", "DP01", "DP02", "DP03", "DD01", "DD03", "DD02"]
LAYOUT: PAIRED

SJDB: "149"

STRANDED: "2"
#STRANDED: 0|1|2
# 0 -> unstranded
# 1 -> forward
# 2 -> reverse

FEATURECOUNTS_PARAM: -t exon -g gene_id
#default count on exons and summarize on gene names, consider -g gene_id
#strandnes and paired-end handled in config.smk
# -O allowMultiOverlap
# -g gene_name
# -s 2
# -p -C ==> paired-end layout


FASTQ_FILTERING: fastq

# GENCODE ---

GENCODE:
    SPECIES: agambiae
    VERSION: "68"
    GENOME: VectorBase-68_AgambiaePEST_Genome
    ANNOTATION: VectorBase-68_AgambiaePEST
    GFF: /home/reference_data/bioinfotree/task/mosquito/VectorBase-68_AgambiaePEST.gff

    # SPECIES: hsapiens
    # hsapiens | mmusculus | mmusculus_hsapiens_combined
    # VERSION: "42"
    # 32 | M23
    # GENOME: GRCh38.primary_assembly
    # GRCh38.primary_assembly | GRCm38.primary_assembly
    # ASSEMBLY: GRCh
    # ANNOTATION: basic.annotation
    # primary_assembly.annotation | basic.annotation

# # TRIMMING ---
# FASTP:
#     adapter_r1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
#     adapter_r2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
# TRIM_GALORE:
#     PARAM:
# # https://support-docs.illumina.com/SHARE/AdapterSequences/Content/SHARE/AdapterSeq/TruSeq/SingleIndexes.htm

# STAR ---
STAR:
    VERSION: "2.7.1a"
    OPTIONS: --outFilterType BySJout --outFilterMultimapNmax 200 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000
    # similar to ENCODE standard options, see STAR manual
    INDEX:
      # GRCh: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/45/GRCh38.p14.star_index/2.7.11a/
      # CHM: /home/reference_data/bioinfotree/task/gencode/dataset/hsapiens/T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0.star_index/2.7.11a/ 
      MOSQ: /home/reference_data/bioinfotree/task/mosquito/VectorBase-68_AgambiaePEST_Genome.star_index/2.7.1a

# DGE ---
DGE:
    DGE_TOOL: edger
    #e.g. DGE_TOOL:=limma|edger|deseq2

    LIMMA_CONTRASTS:
      contrast_name: "contrast"
    #e.g. LIMMA_CONTRASTS:
        # contrast_name: "contrast"
        # KO_vs_WT: "(KO.ND+KO.HFD)-(WT.ND+WT.HFD)"
        # HFD_vs_ND: "(WT.HFD+KO.HFD)-(WT.ND+KO.ND)"
        # WT_HFD_vs_WT_ND: "(WT.HFD-WT.ND)"
        # KO_HFD_vs_KO_ND: "(KO.HFD-KO.ND)"

    LIMMA_DESIGN_FORMULA: "~0+condition"
    #e.g. LIMMA_DESIGN_FORMULA:="~0+condition"

    LIMMA_FACTORS: " "
    #NB: do not comment LIMMA_FACTORS but leave empty if not required
    #e.g. LIMMA_FACTORS:=-f "genotype treatment"

    MIN_NUM_OF_EXPRESSED_SAMPLE: 3
    EXPRESSED_GENES_MIN_CPM: 1
    DGE_CONDITION: "condition" 

# MARK_SEQC ---
MARK_SEQC:
    LOGFC: 1
    PVALUE: 1
    PVALUE_ADJ: 0.05

# DGE HEATMAP ---
HEATMAP:
  COLUMNS: "condition"
  # columns of metadata.txt to add to the heatmap, separated by ,

  N_TOP: "200"
  # number of the top most variant genes to consider for the heatmap

  COLORS: "--pal_set Set3"
  # leave empty if you wish to use the standard colors or specify the custom colorbrewer set to use (default is Set1)

  CLUSTERS: " "
  # indicate the number of clusters the rows (-r) and the columns (-z) will be divided into. 
  # leave empty to have no clusters
  # add -n to show row (gene) names


# DGE VOLCANO PLOT ---
VOLCANO:
  CONTRASTS:
    - BD_vs_KIS
    - BP_vs_KIS
    - DA_vs_KIS
    - DD_vs_KIS
    - DP_vs_KIS

  TITLES:
  # panel titles
    BD_vs_KIS: "BD vs KIS"
    BP_vs_KIS: "BP vs KIS"
    DA_vs_KIS: "DA vs KIS"
    DD_vs_KIS: "DD vs KIS"
    DP_vs_KIS: "DP vs KIS"

  # thresholds
  LFC_CUTOFF: 1
  PADJ_CUTOFF: 0.05
  ALL_CONTRASTS_FILE: "DGE/deseq2.toptable_clean.ALL_contrast.mark_seqc.header_added.gz"

  # Generated mapping (GeneID -> family) will be written here
  FAMILY_MAP_FILE: "/home/reference_data/bioinfotree/task/mosquito/gene_families.tsv"

  # Column names in ALL_CONTRASTS_FILE
  COLUMNS:
    contrast: "contrast"
    gene: "GeneID"
    log2fc: "logFC"
    fdr: "Pvalue_adj"

  OUTPUT:
    pdf: "plots/volcano_panels.pdf"
    png: "plots/volcano_panels.png"
    width_in: 10
    height_in: 8
    dpi: 300
    y_cap: 30
    min_fdr: 1.0e-300
    point_size: 1.6
    base_font_size: 14

  COLORS:
    COE: "red"
    CP: "green"
    CYP: "blue"
    GST: "black"
    SGP: "pink"
    Other: "grey70"
  
  OTHER_LABEL: "Other"
  COLOR_ORDER: ["COE","CP","CYP","GST","SGP","Other"]
  LEGEND_NCOL: 2
  LEGEND_POINT_MM: 3.2
  
  # Layout order and legend cell
  LAYOUT:
    order: ["BD_vs_KIS", "BP_vs_KIS", "DA_vs_KIS", "DD_vs_KIS", "DP_vs_KIS"]
    rel_widths: [1, 1, 1.1]
  